# Generated by Django 5.2.7 on 2025-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_viewer',
            field=models.BooleanField(default=False, help_text='全員の案件を閲覧できますが編集はできません', verbose_name='閲覧者権限'),
        ),
    ]
