# Generated by Django 5.2.7 on 2025-10-03 05:22

from django.db import migrations

def set_default_assigned_to(apps, schema_editor):
    """既存のプロジェクトにassigned_to値を設定"""
    Project = apps.get_model('schedule', 'Project')
    for project in Project.objects.filter(assigned_to__isnull=True):
        # created_byと同じユーザーを担当者に設定
        project.assigned_to = project.created_by
        project.save()

def reverse_set_default_assigned_to(apps, schema_editor):
    """逆マイグレーション（何もしない）"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_project_assigned_to'),
    ]

    operations = [
        migrations.RunPython(set_default_assigned_to, reverse_set_default_assigned_to),
    ]
