# Generated by Django 5.2.7 on 2025-10-03 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_field_data(apps, schema_editor):
    """既存のScheduleデータの分野を新しいFieldモデルに移行"""
    Schedule = apps.get_model('schedule', 'Schedule')
    Field = apps.get_model('schedule', 'Field')
    
    # 既存のchoicesから新しいFieldへのマッピング
    field_mapping = {
        'design': '作図',
        'manufacturing': 'ソフト作成',  # 製造→ソフト作成に変更
        'assembly': '配線',  # 組立→配線に変更
        'testing': 'デバック',  # テスト→デバックに変更
        'delivery': '現地工事',  # 納期→現地工事に変更
        'other': '制御盤',  # その他→制御盤に変更
    }
    
    # 全てのScheduleを更新
    for schedule in Schedule.objects.all():
        if hasattr(schedule, 'field_old'):  # 一時フィールドがある場合
            old_field_value = schedule.field_old
            new_field_name = field_mapping.get(old_field_value, '制御盤')  # デフォルトは制御盤
            try:
                new_field = Field.objects.get(name=new_field_name)
                schedule.field = new_field
                schedule.save()
            except Field.DoesNotExist:
                pass  # Fieldが存在しない場合はスキップ


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_field'),
    ]

    operations = [
        # 1. 既存のfieldフィールドをfield_oldに名前変更
        migrations.RenameField(
            model_name='schedule',
            old_name='field',
            new_name='field_old',
        ),
        # 2. 新しいfield ForeignKeyを追加
        migrations.AddField(
            model_name='schedule',
            name='field',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.field', verbose_name='分野'),
        ),
        # 3. データ移行
        migrations.RunPython(migrate_field_data, migrations.RunPython.noop),
        # 4. 古いfield_oldフィールドを削除
        migrations.RemoveField(
            model_name='schedule',
            name='field_old',
        ),
        # 5. fieldを必須に変更
        migrations.AlterField(
            model_name='schedule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.field', verbose_name='分野'),
        ),
    ]
