# Generated by Django 5.2.7 on 2025-10-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_migrate_schedule_field_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完了日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', '予定'), ('in_progress', '進行中'), ('completed', '完了')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
