# Generated by Django 5.2.7 on 2025-10-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_completed_at_schedule_status'),
    ]

    operations = [
    ]
