# Generated by Django 5.2.7 on 2025-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_update_existing_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
    ]
