# Generated by Django 5.2.7 on 2025-10-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完了日時'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
    ]
